export const FETCH_RESTUARANT_DETAILS = "/restaurantDetails/FETCH_RESTUARANT_DETAILS"
export const FETCH_RESTUARANT_DETAILS_SUCCESS = "/restaurantDetails/FETCH_RESTUARANT_DETAILS_SUCCESS"
export const FETCH_RESTUARANT_DETAILS_FAILED = "/restaurantDetails/FETCH_RESTUARANT_DETAILS_FAILED"
export const UPDATE_RESTUARANT_DETAILS = '/restaurantDetails/UPDATE_RESTUARANT_DETAILS'
